---
title: "Conard, March 7, 2023"
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

library(readxl)
library(tidyverse)
library(gt)
library(cowplot)
```

```{r data manip, include=FALSE}
bb_players23 <- read_xlsx("BB_players23.xlsx")
bb_players23$`eFG%` <-as.numeric(bb_players23$`eFG%`)
bb_players23$`TO%` <-as.numeric(bb_players23$`TO%`)

athletes <- c("Chad Rizzo", "DJ Hawkins", "Excel Adekola",
              "Kit Scudder", "Nicholas Bergin", "Jahkai Veal", 
              "Caleb Smith")

max <- max(bb_players23$Game, na.rm = T)

bb_seven_players <- bb_players23 %>% filter(Athletes %in% athletes)

```

```{r, fig.width = 7.5, fig.height = 5, echo=FALSE}
eFG <- bb_seven_players %>% filter(Game == max) %>% 
  ggplot(aes(x = reorder(Athletes, `eFG%`), 
             y = `eFG%`)) + 
  geom_col() + 
  coord_flip() +
  theme_light()+
  labs(title = "Conard - eFG%",
       subtitle = "March 7, 2023",
       x = "",
       legend = "")

TO <- bb_seven_players %>% filter(Game == max) %>%
  ggplot(aes(x = reorder(Athletes, -`TO%`), y = `TO%`)) +
  geom_col() + 
  coord_flip()+
  theme_light()+
  labs(title = "Conard - TO%",
       subtitle = "March 7, 2023",
       x = "",
       legend = "")
  

FTF <- bb_seven_players %>% filter(Game == max) %>% 
  ggplot(aes(x = reorder(Athletes, FTF), y = FTF)) + 
  geom_col() + 
  coord_flip() +
  theme_light()+
  labs(title = "Conard - FTF",
       subtitle = "March 7, 2023",
       x = "",
       legend = "")

VPS <- bb_seven_players %>% filter(Game == max) %>% 
  ggplot(aes(x = reorder(Athletes, VPS), y = VPS)) + 
  geom_col() + 
  coord_flip() +
  theme_light()+
  labs(title = "Conard - VPS",
       subtitle = "March 7, 2023",
       x = "",
       legend = "")

plot_grid(eFG, TO, FTF, VPS)
```

